//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHGameOfLife {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LargePops {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LargePops() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHGameOfLife.LargePops", typeof(LargePops).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOO..........
        ///O.........OO.
        ///.O......OOO.O
        ///...OO..OO....
        ///....O........
        ///........O....
        ///....OO...O...
        ///...O.O.OO....
        ///...O.O..O.OO.
        ///..O....OO....
        ///..OO.........
        ///..OO..........
        /// </summary>
        internal static string Canada_Goose {
            get {
                return ResourceManager.GetString("Canada_Goose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ........OO.......
        ///.......OO........
        ///.........O.......
        ///...........OO....
        ///..........O......
        ///.................
        ///.........O..OO...
        ///.OO.....OO....O..
        ///OO.....O.....O...
        ///..O....O.O...OO..
        ///....O..O....OO.O.
        ///....OO.......OO..
        ///........O....O.OO
        ///.......O.O..O.OO.
        ///........O.........
        /// </summary>
        internal static string Grow_By_One {
            get {
                return ResourceManager.GetString("Grow_By_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....OO......OO....
        ///...O..O....O..O...
        ///...O.O......O.O...
        ///.OO..OOO..OOO..OO.
        ///O......O..O......O
        ///O.OO..........OO.O
        ///.O.O..........O.O.
        ///...OO...OO...OO...
        ///.......O.O........
        ///.......OO.........
        ///...OO........OO...
        ///.O.O..........O.O.
        ///O.OO..........OO.O
        ///O......O..O......O
        ///.OO..OOO..OOO..OO.
        ///...O.O......O.O...
        ///...O..O....O..O...
        ///....OO......OO.....
        /// </summary>
        internal static string Ship_In_a_Bottle {
            get {
                return ResourceManager.GetString("Ship_In_a_Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..........O....................
        ///..........O...............OO...
        ///......OO.O.OOO..........OO...O.
        ///O.OO.OO.OO..O.O...OO.OOOO......
        ///O...OO..O.OO..OOO..O.OO..OO...O
        ///O.OO....OOO.O.OOO......OO..O...
        ///........OO.O...............O..O
        ///O.OO....OOO.O.OOO......OO..O...
        ///O...OO..O.OO..OOO..O.OO..OO...O
        ///O.OO.OO.OO..O.O...OO.OOOO......
        ///......OO.O.OOO..........OO...O.
        ///..........O...............OO...
        ///..........O.....................
        /// </summary>
        internal static string Sparky {
            get {
                return ResourceManager.GetString("Sparky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .OO........................
        ///.OO........................
        ///...........................
        ///...............O...........
        ///OO.............OO........OO
        ///OO..............OO.......OO
        ///...........OO..OO..........
        ///...........................
        ///...........................
        ///...........................
        ///...........OO..OO..........
        ///OO..............OO.........
        ///OO.............OO..........
        ///...............O...........
        ///...........................
        ///.OO........................
        ///.OO.........................
        /// </summary>
        internal static string Twin_Bees {
            get {
                return ResourceManager.GetString("Twin_Bees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .................OO..............................
        ///.............OO....O.............................
        ///............OOO.O................................
        ///O.OO..OO...O...OOOO.O.O....OO.......OO...........
        ///O....OO..O........O.OOO....O....OO.O..O.OO.O.....
        ///O.OO....OO.OO....O...........O...O.O.OO.O.OO.....
        ///......O.......O.............OO.....O..O.O...OO...
        ///.....O.........O.O....OOO...O....O..O.O.OOO...O..
        ///.....O.........O.O....OOO.OO.O..OO.O.O...O..OO.O.
        ///......O.......O.............OO.O...OO....OO....O.
        ///O. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wickstretcher {
            get {
                return ResourceManager.GetString("Wickstretcher", resourceCulture);
            }
        }
    }
}
