//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHGameOfLife {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LargePops {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LargePops() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHGameOfLife.LargePops", typeof(LargePops).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 104P177
        ///!Author: Karel Suhajda
        ///!A period 177 oscillator discovered by Karel Suhajda in June 2007
        ///!http://www.conwaylife.com/wiki/index.php?title=104P177
        ///................O............O
        ///.........OO........................OO
        ///........OOO...OO..............OO...OOO
        ///..............OO.OO........OO.OO
        ///................O............O
        ///
        ///
        ///
        ///..O........................................O
        ///.OO........................................OO
        ///.OO........................................OO
        ///
        ///
        ///
        ///..OO............... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _104p177 {
            get {
                return ResourceManager.GetString("_104p177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 119P4H1V0
        ///!Author: Dean Hickerson
        ///!The first c/4 orthogonal spaceship to be discovered
        ///!http://www.conwaylife.com/wiki/index.php?title=119P4H1V0
        ///.................................O
        ///................O...............O.O
        ///......O.O......O.....OO........O
        ///......O....O....O.OOOOOO....OO
        ///......O.OOOOOOOO..........O..O.OOO
        ///.........O.....O.......OOOO....OOO
        ///....OO.................OOO.O
        ///.O..OO.......OO........OO
        ///.O..O
        ///O
        ///.O..O
        ///.O..OO.......OO........OO
        ///....OO.................OOO.O
        ///.........O.... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _119p4h1v0 {
            get {
                return ResourceManager.GetString("_119p4h1v0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 1-2-3
        ///!Author: Dave Buckingham
        ///!Found in August 1972.
        ///!This is one of only three essentially different p3 oscillators with only three cells in the rotor. The others are stillater and cuphook.
        ///..OO
        ///O..O
        ///OO.O.OO
        ///.O.O..O
        ///.O....O.OO
        ///..OOO.O.OO
        ///.....O
        ///....O
        ///....OO
        ///.
        /// </summary>
        internal static string _123 {
            get {
                return ResourceManager.GetString("_123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 17c/45_Reaction
        ///!A reaction between a pi-heptomino and a blinker in which the pi moves forward 17 cells in the course of 45 generations while the blinker moves back 6 cells and is rephased.
        ///...............O
        ///O.............OO
        ///O............OO
        ///O.............OO
        ///...............O
        ///.
        /// </summary>
        internal static string _17c45reaction {
            get {
                return ResourceManager.GetString("_17c45reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 1 beacon
        ///!Approximately the 32nd-most common oscillator.
        ///!www.conwaylife.com/wiki/index.php?title=1_beacon
        ///..OO
        ///.O.O
        ///O..O.OO
        ///OO.O..O
        ///.O.O
        ///.O..O
        ///..OO
        ///.
        /// </summary>
        internal static string _1beacon {
            get {
                return ResourceManager.GetString("_1beacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 158P3 on Achim&apos;s p11
        ///!Author: Noam Elkies and Achim Flammenkamp
        ///!The first known non-trivial period 33 oscillator
        ///..........OO
        ///..........OO
        ///.....O..........O
        ///....O.O........O.O..........OO.O.O....O
        ///...O.O...O..O...O.O........O.O.OO.O..O.O...OO
        ///..O.O....O..O....O.O.....OOO..O...OOOO.O...OO
        ///...O.....O..O.....O.....O...O.O.OO....O
        ///.........................O..O..O.O.OO....OOOO..OO
        ///.........................O.OO.O..O..OO..O....O..O
        ///....OOO........OOO..........O...O.O....O.O..O.OO
        ///OO........... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _258p3onachimsp11 {
            get {
                return ResourceManager.GetString("_258p3onachimsp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 2 fumaroles
        ///!Author: Noam Elkies
        ///!A non-trivial combination of two fumaroles and a blinker, found on September 1, 1995.
        ///!www.conwaylife.com/wiki/index.php?title=Fumarole
        ///OO
        ///O..OO....O
        ///.OO.OO...O
        ///....OO...O
        ///....OO
        ///.OO.OO....OO
        ///O..OO...O....O
        ///OO......O....O
        ///........O....O
        ///.........O..O
        ///.......O.O..O.O
        ///.......OO....OO
        ///.
        /// </summary>
        internal static string _2fumaroles {
            get {
                return ResourceManager.GetString("_2fumaroles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 46P4H1V0
        ///!The smallest known c/4 orthogonal spaceship.
        ///!www.conwaylife.com/wiki/index.php?title=46P4H1V0
        ///...O...........O
        ///...O...........O
        ///..O.O.........O.O
        ///
        ///.O...O.......O...O
        ///.O.OOOOOO.OOOOOO.O
        ///O.......O.O.......O
        ///O.......O.O.......O
        ///O.................O
        ///.O.OO.OO...OO.OO.O
        ///.
        /// </summary>
        internal static string _46p4h1v0 {
            get {
                return ResourceManager.GetString("_46p4h1v0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 4-8-12_diamond
        ///!A pure glider generator.
        ///....OOOO
        ///
        ///..OOOOOOOO
        ///
        ///OOOOOOOOOOOO
        ///
        ///..OOOOOOOO
        ///
        ///....OOOO
        ///.
        /// </summary>
        internal static string _4812diamond {
            get {
                return ResourceManager.GetString("_4812diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 86P5H1V1
        ///!Author: Jason Summers
        ///!The second c/5 diagonal spaceship to be discovered
        ///!http://www.conwaylife.com/wiki/index.php?title=86P5H1V1
        ///.........OOO
        ///........O
        ///.......O
        ///...........OO
        ///........OO.O
        ///..............OOO
        ///...........O..OO..OO
        ///..O........OO.O...OO
        ///.O..O......O..OO
        ///O...O
        ///O...........O..O
        ///O..OO.OOO...O...OO.OO
        ///...O...O..OO..O..O
        ///.................OO..O
        ///.....OOOO...O.....O...O
        ///.....OO.O.O..........O
        ///.....O.....O......OO
        ///...........OOO
        ///......OO.....OO.O
        ///......OO...O....O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _86p5h1v1 {
            get {
                return ResourceManager.GetString("_86p5h1v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: 92P33.1
        ///!Author: Jason Summers
        ///!The smallest known period 33 oscillator as of April 2009. Found on August 31, 2000.
        ///!www.conwaylife.com/wiki/index.php?title=92P33.1
        ///.....................O
        ///....O..O...OOOOO..OOO.O
        ///....O..O.......O..O..O
        ///.O.OO..OOOOO...O..O
        ///O.O
        ///.O
        ///
        ///
        ///
        ///
        ///
        ///
        ///......O.O...OOOO
        ///......O..O..O..O
        ///......O.....OOO..........OO
        ///.......OO..........OOO.....O
        ///..................O..O..O..O
        ///..................OOOO...O.O
        ///
        ///
        ///
        ///
        ///
        ///
        ///................................O
        ///................... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _92p331 {
            get {
                return ResourceManager.GetString("_92p331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Anvil
        ///!An induction coil.
        ///.OOOO
        ///O....O
        ///.OOO.O
        ///...O.OO
        ///.
        /// </summary>
        internal static string anvil {
            get {
                return ResourceManager.GetString("anvil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: aVerage
        ///!Author: David Buckingham
        ///!The average number of live rotor cells is five (V), which is also the period.
        ///!www.conwaylife.com/wiki/index.php?title=AVerage
        ///...OO
        ///....OOO
        ///..O....O
        ///.O.OOOO.O
        ///.O.O....O..O
        ///OO.OOO..O.O.O
        ///.O.O....O..O
        ///.O.OOOO.O
        ///..O....O
        ///....OOO
        ///...OO
        ///.
        /// </summary>
        internal static string average {
            get {
                return ResourceManager.GetString("average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: B29
        ///!Author: Hartmut Holzwart
        ///!A small c/4 diagonal spaceship with an isolated domino spark; discovered in September 2004
        ///!http://www.conwaylife.com/wiki/index.php?title=B29
        ///...OO
        ///..OO
        ///....O
        ///......OO
        ///.....O
        ///
        ///....O..O
        ///.OO.O
        ///OO....O
        ///..O.O..O
        ///.......O
        ///....O..O
        ///.....O.O
        ///.....O.O
        ///......OO
        ///......O
        ///.
        /// </summary>
        internal static string b29 {
            get {
                return ResourceManager.GetString("b29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: B-52 bomber
        ///!Author: Noam Elkies
        ///!A period 104 double-barrelled glider gun. It uses a B-heptomino and emits one glider every 52 generations.
        ///!www.conwaylife.com/wiki/index.php?title=B-52_bomber
        ///.OO
        ///.OO.................O
        ///...................O.O............O.O
        ///....................O............O
        ///OO.......OO.......................O..O
        ///OO.O.....OO.......................O.O.O
        ///...O.......................O.......O..O
        ///...O.......................OO.......OO
        ///O..O.................OO.....O
        ///.OO........ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string b52bomber {
            get {
                return ResourceManager.GetString("b52bomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Backrake 3
        ///!A pseudo period 32 (true period 64) orthogonal c/2 backrake based on puffer 1.
        ///!http://www.conwaylife.com/wiki/index.php?title=Backrake_3
        ///....OOO......O.....O......OOO
        ///....O..O....OOO...OOO....O..O
        ///....O.......O.OO.OO.O.......O
        ///....O...O...............O...O
        ///....O...O...............O...O
        ///....O.....O..O.....O..O.....O
        ///.....O.O...OO.O...O.OO...O.O
        ///............OO.....OO
        ///
        ///
        ///
        ///..OOO.......................OOO
        ///.O..O.......................O..O
        ///....O.......................O
        ///O...O.... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string backrake3 {
            get {
                return ResourceManager.GetString("backrake3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Barge 2 (spaceship)
        ///!Author: Hartmut Holzwart
        ///!A period 2 c/2 orthogonal extendable spaceship.
        ///!www.conwaylife.com/wiki/index.php?title=Barge_2_(spaceship)
        ///..............OOO.OOO
        ///.............O..O.O..O
        ///............O...O.O...O
        ///.......OOO.O..O.O.O.O..O.OOO
        ///......O..O.O....O.O....O.O..O
        ///.....O...O.O.O.O...O.O.O.O...O
        ///.....O.......................O
        ///.......O...................O
        ///....O.O.....................O.O
        ///...OO.O.OOO.............OOO.O.OO
        ///..O.O.O...O.............O...O.O.O
        ///.OO.O........... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string barge2spaceship {
            get {
                return ResourceManager.GetString("barge2spaceship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Barge (spaceship)
        ///!Author: Hartmut Holzwart and David Bell
        ///!A period 3 c/3 orthogonal extendable spaceship.
        ///!www.conwaylife.com/wiki/index.php?title=Barge_(spaceship)
        ///.......O.............................................O
        ///.....OOOO.....OOO...........................OOO.....OOOO
        ///.OO.OO...O...O.................................O...O...OO.OO
        ///.OO..O.....OOO....O...O...............O...O....OOO.....O..OO
        ///O..O.......O.O.OOOOO.OOOO...........OOOO.OOOOO.O.O.......O..O
        ///.........O......O..O.O...O.OO...O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bargespaceship {
            get {
                return ResourceManager.GetString("bargespaceship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Bee hat
        ///!The 75th most common still life.
        ///!http://www.conwaylife.com/wiki/index.php?title=Bee_hat
        ///.OO
        ///O..O
        ///.OO.O
        ///..O.O
        ///O.O.OO
        ///OO.
        /// </summary>
        internal static string Bee_Hat {
            get {
                return ResourceManager.GetString("Bee_Hat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Beehive bend tail
        ///!The 88th most common still life.
        ///!http://www.conwaylife.com/wiki/index.php?title=Beehive_bend_tail
        ///.OO
        ///O..O
        ///.OO.O
        ///....O
        ///.OOO
        ///.O
        ///.
        /// </summary>
        internal static string beehivebendtail {
            get {
                return ResourceManager.GetString("beehivebendtail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Beehive with nine
        ///!The 89th most common still life.
        ///!http://www.conwaylife.com/wiki/index.php?title=Beehive_with_nine
        ///.OO
        ///O..O
        ///.OO.O
        ///....O
        ///....O.O
        ///.....OO
        ///.
        /// </summary>
        internal static string beehivewithnine {
            get {
                return ResourceManager.GetString("beehivewithnine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Blinker puffer 1
        ///!Author: Robert Wainwright
        ///!The first blinker puffer to be found.
        ///!www.conwaylife.com/wiki/index.php?title=Blinker_puffer_1
        ///...O
        ///.O...O
        ///O
        ///O....O
        ///OOOOO
        ///
        ///
        ///
        ///.OO
        ///OO.OOO
        ///.OOOO
        ///..OO
        ///
        ///.....OO
        ///...O....O
        ///..O
        ///..O.....O
        ///..OOOOOO
        ///.
        /// </summary>
        internal static string blinkerpuffer1 {
            get {
                return ResourceManager.GetString("blinkerpuffer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Blinkers bit pole
        ///!Author: Robert Wainwright
        ///!A period 2 oscillator found in June 1977.
        ///!www.conwaylife.com/wiki/index.php?title=Blinkers_bit_pole
        ///.....OO
        ///OOO.O.O
        ///
        ///.O.O..O
        ///O....O
        ///OO...O
        ///.
        /// </summary>
        internal static string blinkersbitpole {
            get {
                return ResourceManager.GetString("blinkersbitpole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Boatstretcher 1
        ///!Author: Hartmut Holzwart
        ///!The first diagonal wickstretcher to be found
        ///!http://www.conwaylife.com/wiki/index.php?title=Boatstretcher_1
        ///..........O
        ///.........OO
        ///.........O.O...O
        ///.............OO
        ///..............O..O
        ///............OO.O..O
        ///........OOO.OO....O
        ///.......O..O....O
        ///......O....O....OO
        ///.OO...O.....O.O.OO
        ///OO....OO.........O
        ///..O.....O.........O
        ///.....OO..O......OOO
        ///...O.OO...........O.O
        ///...OO....O.........OO
        ///..O..O.O
        ///........OO..O
        ///....O...OOO.O
        ///.....OO....OOO
        ///.... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string boatstretcher1 {
            get {
                return ResourceManager.GetString("boatstretcher1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Boat with long tail
        ///!A small still life.
        ///!http://www.conwaylife.com/wiki/index.php?title=Boat_with_long_tail
        ///OO
        ///O.O
        ///.O..OO
        ///..OO.O
        ///.
        /// </summary>
        internal static string boatwithlongtail {
            get {
                return ResourceManager.GetString("boatwithlongtail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Brain
        ///!Author: David Bell
        ///!An orthogonal period 3 spaceship.
        ///!www.conwaylife.com/wiki/index.php?title=Brain
        ///.OOO.........OOO
        ///O.O.OO.....OO.O.O
        ///O.O.O.......O.O.O
        ///.O.OO.OO.OO.OO.O
        ///.....O.O.O.O
        ///...O.O.O.O.O.O
        ///..OO.O.O.O.O.OO
        ///..OOO..O.O..OOO
        ///..OO..O...O..OO
        ///.O....OO.OO....O
        ///.O.............O
        ///.
        /// </summary>
        internal static string brain {
            get {
                return ResourceManager.GetString("brain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Buckaroo
        ///!Author: David Buckingham
        ///!A period 30 oscillator based on the queen bee shuttle.
        ///!The oscillator will still function if the eater is moved
        ///!closer to the queen bee by one space, but it will lose
        ///!its ability to reflect gliders.
        ///!www.conwaylife.com/wiki/index.php?title=Buckaroo
        ///.........O
        ///.......O.O
        ///......O.O
        ///OO...O..O
        ///OO....O.O
        ///.......O.O.........OO
        ///.........O.........O.O
        ///.....................O
        ///.....................OO
        ///.
        /// </summary>
        internal static string buckaroo {
            get {
                return ResourceManager.GetString("buckaroo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Bunnies 10
        ///!Author: Tomas Rokicki
        ///!A methuselah with lifespan 17423 that evolves similarly to bunnies after generation 104.
        ///!www.conwaylife.com/wiki/index.php?title=Bunnies_10
        ///.O
        ///OO.O
        ///....OO
        ///O..O
        ///O
        ///O
        ///.
        /// </summary>
        internal static string bunnies10 {
            get {
                return ResourceManager.GetString("bunnies10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOO..........
        ///O.........OO.
        ///.O......OOO.O
        ///...OO..OO....
        ///....O........
        ///........O....
        ///....OO...O...
        ///...O.O.OO....
        ///...O.O..O.OO.
        ///..O....OO....
        ///..OO.........
        ///..OO..........
        /// </summary>
        internal static string Canada_Goose {
            get {
                return ResourceManager.GetString("Canada_Goose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Carnival shuttle
        ///!Author: Robert Wainwright
        ///!A period 12 oscillator.
        ///!www.conwaylife.com/wiki/index.php?title=Carnival_shuttle
        ///.................................O...O
        ///OO...OO..........................OOOOO
        ///.O.O.O...O..O......OO...O..O.......O
        ///.OO.OO..OO...OO....OO..OO...OO....O.O
        ///.O.O.O...O..O......OO...O..O.......O
        ///OO...OO..........................OOOOO
        ///.................................O...O
        ///.
        /// </summary>
        internal static string carnivalshuttle {
            get {
                return ResourceManager.GetString("carnivalshuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Carrier siamese carrier
        ///!A still life composed of two aircraft carriers attached together.
        ///!http://www.conwaylife.com/wiki/index.php?title=Carrier_siamese_carrier
        ///OO
        ///O..OO
        ///..OO..O
        ///.....OO
        ///.
        /// </summary>
        internal static string carriersiamesecarrier {
            get {
                return ResourceManager.GetString("carriersiamesecarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: C-heptomino
        ///!A methuselah with lifespan 148 that evolves in the same way as the B-heptomino after its second generation.
        ///!http://www.conwaylife.com/wiki/index.php?title=C-heptomino
        ///.OOO
        ///OOO
        ///.O
        ///.
        /// </summary>
        internal static string cheptomino {
            get {
                return ResourceManager.GetString("cheptomino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Cis-barge with tail
        ///!A still life.
        ///!http://www.conwaylife.com/wiki/index.php?title=Cis-barge_with_tail
        ///...O
        ///..O.O
        ///.O.O.O
        ///.O..O
        ///OO
        ///.
        /// </summary>
        internal static string cisbargewithtail {
            get {
                return ResourceManager.GetString("cisbargewithtail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Cis-beacon and dock
        ///!A period 2 oscillator.
        ///!www.conwaylife.com/wiki/index.php?title=Cis-beacon_and_dock
        ///...OO
        ///....O
        ///.O
        ///.OO
        ///
        ///.OOOO
        ///O....O
        ///OO..OO
        ///.
        /// </summary>
        internal static string cisbeaconanddock {
            get {
                return ResourceManager.GetString("cisbeaconanddock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Cis-beacon up and long hook
        ///!A period two oscillator composed of a beacon and a long hook.
        ///!www.conwaylife.com/wiki/index.php?title=Beacon_and_long_hook
        ///..OO
        ///...O
        ///O
        ///OO
        ///
        ///OOOO
        ///O...O
        ///...OO
        ///.
        /// </summary>
        internal static string cisbeaconupandlonghook {
            get {
                return ResourceManager.GetString("cisbeaconupandlonghook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Cis-boat and dock
        ///!The fifty-seventh most common still life.
        ///!http://www.conwaylife.com/wiki/index.php?title=Cis-boat_and_dock
        ///..O
        ///.O.O
        ///.OO
        ///
        ///.OOOO
        ///O....O
        ///OO..OO
        ///.
        /// </summary>
        internal static string cisboatanddock {
            get {
                return ResourceManager.GetString("cisboatanddock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Cis-mirrored R-bee
        ///!A still life made up of two buns facing each other.
        ///!http://www.conwaylife.com/wiki/index.php?title=Cis-mirrored_R-bee
        ///.OO.OO
        ///O.O.O.O
        ///O.O.O.O
        ///.O...O
        ///.
        /// </summary>
        internal static string cismirroredrbee {
            get {
                return ResourceManager.GetString("cismirroredrbee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Cis-shillelagh
        ///!A small still life similar to the long long shillelagh.
        ///!http://www.conwaylife.com/wiki/index.php?title=Cis-shillelagh
        ///....OO
        ///.....O
        ///OO..O
        ///O..O
        ///.OO
        ///.
        /// </summary>
        internal static string cisshillelagh {
            get {
                return ResourceManager.GetString("cisshillelagh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Confused eaters
        ///!Author: David Buckingham
        ///!A period 4 oscillator found no later than 1972.
        ///!www.conwaylife.com/wiki/index.php?title=Confused_eaters
        ///O
        ///OOO
        ///...O
        ///..O
        ///..O..O
        ///.....O
        ///...O.O
        ///...OO..OO
        ///.......O.O
        ///.........O
        ///.........OO
        ///.
        /// </summary>
        internal static string confusedeaters {
            get {
                return ResourceManager.GetString("confusedeaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Edge-repair spaceship 1
        ///!Author: David Bell
        ///!An edge-repair spaceship that was found in 1992.
        ///!www.conwaylife.com/wiki/index.php?title=Edge-repair_spaceship_1
        ///........O
        ///.......OOOO
        ///..O...O...OO.OO
        ///.OOOO.....O..OO
        ///O...O.......O..O
        ///.O.O..O
        ///.....O
        ///.
        /// </summary>
        internal static string edgerepairspaceship1 {
            get {
                return ResourceManager.GetString("edgerepairspaceship1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Edna
        ///!Author: Erik de Neve
        ///!A methuselah with lifespan 31,192.
        ///!www.conwaylife.com/wiki/index.php?title=Edna
        ///..O..O..O.....O....O
        ///..OO....O..O..OO.O
        ///.OOOO.OO.OOOO.O.O.O
        ///OO.O.....OO.OO..OOO
        ///........O..O..OOO
        ///OOO.OO...O..O..O...O
        ///.OOOO.....O..OOO..OO
        ///O.O..O...O.....O.O
        ///OO.O.OO.OOO.O
        ///..O..OO.....O.O..O.O
        ///OO..O.O.OO...O..OO
        ///....O.O...O.O....OO
        ///.O..O.O....O..OO
        ///OOO...O...O....OOOO
        ///OO.OO......O....O..O
        ///.....O...O.O......OO
        ///......O..O.....O.O
        ///........O..O..O.O
        ///..OOOO.O..O.OO.....O
        ///O.O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string edna {
            get {
                return ResourceManager.GetString("edna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Ellison p4 HW emulator hybrid
        ///!Author: Scot Ellison
        ///!A period 4 oscillator that produces a domino spark.
        ///!www.conwaylife.com/wiki/Ellison_P4_HW_Emulator_Hybrid
        ///...........OO
        ///....O...O.....O.OO
        ///...O.O...........O
        ///...O.O.........OO
        ///OO.O.O.OOOOOOOO..OOO
        ///OO.O............O..O
        ///...O.............OO
        ///...O.O....OO
        ///....OO....OO
        ///.
        /// </summary>
        internal static string ellisonp4hwemulatorhybrid {
            get {
                return ResourceManager.GetString("ellisonp4hwemulatorhybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Eureka
        ///!Author: David Buckingham
        ///!A period 30 pre-pulsar shuttle found in August 1980.
        ///!www.conwaylife.com/wiki/index.php?title=Eureka
        ///.O..............O
        ///O.O....O.......O.O
        ///.O...OO.OO......O
        ///.......O
        ///
        ///
        ///
        ///.......O
        ///.O...OO.OO......O
        ///O.O....O.......O.O
        ///.O..............O
        ///.
        /// </summary>
        internal static string eureka {
            get {
                return ResourceManager.GetString("eureka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Extremely impressive
        ///!Author: David Buckingham
        ///!A period 6 oscillator found in August 1976.
        ///!www.conwaylife.com/wiki/index.php?title=Extremely_impressive
        ///....OO
        ///...O.OOO
        ///...O....O
        ///OO.O...OO
        ///OO.O.....OO
        ///....OOOOO..O
        ///..........OO
        ///......O
        ///.....O.O
        ///......O
        ///.
        /// </summary>
        internal static string extremelyimpressive {
            get {
                return ResourceManager.GetString("extremelyimpressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Fumarole
        ///!Author: Dean Hickerson
        ///!A period 5 oscillator found in September 1989.
        ///!www.conwaylife.com/wiki/index.php?title=Fumarole
        ///...OO
        ///.O....O
        ///.O....O
        ///.O....O
        ///..O..O
        ///O.O..O.O
        ///OO....OO
        ///.
        /// </summary>
        internal static string fumarole {
            get {
                return ResourceManager.GetString("fumarole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Fumarole on Achim&apos;s p11
        ///!A small non-trivial period 55 oscillator.
        ///!www.conwaylife.com/wiki/index.php?title=Fumarole_on_Achim&apos;s_p11
        ///..........OO
        ///..........OO
        ///.....O..........O
        ///....O.O........O.O
        ///...O.O..........O.O
        ///..O.O...OOOOOO...O.O
        ///...O..............O
        ///
        ///.....O..........O
        ///.....O..........O
        ///OO...O..........O...OO
        ///OO...O..........O...OO
        ///.....O..........O
        ///.....O..........O..........OO
        ///.......................OOO..O
        ///...O..............O.......OO
        ///..O.O...OOOOOO...O.O..O
        ///...O.O......... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fumaroleonachimsp11 {
            get {
                return ResourceManager.GetString("fumaroleonachimsp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Garden of Eden 1
        ///!Author: Roger Banks
        ///!The first Garden of Eden that was explicitly constructed. Found in 1971.
        ///!www.conwaylife.com/wiki/index.php?title=Garden_of_Eden_1
        ///OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        ///OO.O.OOO.OOO.OO.O.O.O.O.O.O.O.O.O
        ///O.O.OOO.OOO.OOOO.OOO.O.O.O.O.O.O
        ///OOOOO.OOO.OOO.OOOO.OOOOOOOOOOOOOO
        ///O.O.OO.OOO.OOO.O.OOO.O.O.O.O.O.O
        ///OOOO.OOO.OOO.OOOOO.OO.O.O.O.O.O.O
        ///.OO.OOO.OOO.OOO.O.O.OOOOOOOOOOOOO
        ///OO.OO.OOO.OOO.OO.OOOO.O.O.O.O.O.O
        ///OOOOOOOOOOOOOOOOOO.OOOOOOOOOOOOOO
        ///.
        /// </summary>
        internal static string gardenofeden1 {
            get {
                return ResourceManager.GetString("gardenofeden1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Garden of Eden 5
        ///!Author: Nicolay Beluchenko
        ///!Currently the smallest-known Garden of Eden in Conway&apos;s Game of Life.
        ///!www.conwaylife.com/wiki/index.php?title=Garden_of_Eden_5
        ///.OOO..OO
        ///.OO.O.O.OOO
        ///.OOO..OOOOO
        ///O.O.O.O.O.O
        ///OOOO.O.O.O
        ///....OOO
        ///.O.O.O.OOOO
        ///O.O.O.O.O.O
        ///OOOOO..OOO
        ///OOO.O.O.OO
        ///...OO..OOO
        ///.
        /// </summary>
        internal static string gardenofeden5 {
            get {
                return ResourceManager.GetString("gardenofeden5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Germ
        ///!Author: David Buckingham
        ///!A period 3 oscillator found in September 1972.
        ///!www.conwaylife.com/wiki/index.php?title=Germ
        ///....OO
        ///.....O
        ///...O
        ///..O.OOOO
        ///..O....O
        ///.OO.O
        ///..O.O.OOOO
        ///O.O.O....O
        ///OO...OOO
        ///.......OO
        ///.
        /// </summary>
        internal static string germ {
            get {
                return ResourceManager.GetString("germ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Glasses
        ///!A period 2 oscillator.
        ///!www.conwaylife.com/wiki/index.php?title=Glasses
        ///....O........O
        ///..OOO........OOO
        ///.O..............O
        ///.O..OOO....OOO..O
        ///OO.O...O..O...O.OO
        ///...O...OOOO...O
        ///...O...O..O...O
        ///....OOO....OOO
        ///
        ///....OO.O..O.OO
        ///....O.OO..OO.O
        ///.
        /// </summary>
        internal static string glasses {
            get {
                return ResourceManager.GetString("glasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ........OO.......
        ///.......OO........
        ///.........O.......
        ///...........OO....
        ///..........O......
        ///.................
        ///.........O..OO...
        ///.OO.....OO....O..
        ///OO.....O.....O...
        ///..O....O.O...OO..
        ///....O..O....OO.O.
        ///....OO.......OO..
        ///........O....O.OO
        ///.......O.O..O.OO.
        ///........O.........
        /// </summary>
        internal static string Grow_By_One {
            get {
                return ResourceManager.GetString("Grow_By_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Heart
        ///!A period 5 oscillator.
        ///!www.conwaylife.com/wiki/Heart
        ///.....O
        ///....O..O
        ///.O..O..O
        ///O.O.O.O.OO
        ///.O..O..O
        ///....O.....O
        ///.....OOOOO
        ///
        ///.......O
        ///......O.O
        ///.......O
        ///.
        /// </summary>
        internal static string heart {
            get {
                return ResourceManager.GetString("heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Heavyweight emulator
        ///!Author: Robert Wainwright
        ///!A period 4 oscillator that produces sparks similar to that of the heavyweight spaceship.
        ///!www.conwaylife.com/wiki/index.php?title=Heavyweight_emulator
        ///.......OO
        ///..OO.O....O.OO
        ///..O..........O
        ///...OO......OO
        ///OOO..OOOOOO..OOO
        ///O..O........O..O
        ///.OO..........OO
        ///.
        /// </summary>
        internal static string heavyweightemulator {
            get {
                return ResourceManager.GetString("heavyweightemulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Heavyweight volcano
        ///!Author: Dean Hickerson
        ///!A period 5 oscillator found in February 1995 that gives off a domino spark much like a heavyweight spaceship.
        ///!www.conwaylife.com/wiki/index.php?title=Heavyweight_volcano
        ///......O
        ///.....O.O
        ///...OOO.O
        ///..O....OO.O
        ///..O.OO...OO......OO
        ///.OO.O.OO.........O.O
        ///O...O...OOOOO......O..O.OO
        ///OO.OO..O.....O....OO.O.OO.O
        ///O........O..OO.......O....O
        ///OO.O....O.O..OO....OO.OOOO.OO
        ///OO.O..O..OO..OOOO.O.O.O....O.O
        ///O.....O...O..OO.O.OO..O..OO..O
        ///OO.OO.O........O.O. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string heavyweightvolcano {
            get {
                return ResourceManager.GetString("heavyweightvolcano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Hivenudger
        ///!Author: Hartmut Holzwart
        ///!A pre-beehive escorted by four lightweight spaceships.
        ///!www.conwaylife.com/wiki/index.php?title=Hivenudger
        ///OOOO.....O..O
        ///O...O...O
        ///O.......O...O
        ///.O..O...OOOO
        ///
        ///.....OO
        ///.....OO
        ///.....OO
        ///
        ///.O..O...OOOO
        ///O.......O...O
        ///O...O...O
        ///OOOO.....O..O
        ///.
        /// </summary>
        internal static string hivenudger {
            get {
                return ResourceManager.GetString("hivenudger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Hivenudger 2
        ///!A line puffer based on the hivenudger. It leaves a trail of blinkers behind it.
        ///!www.conwaylife.com/wiki/index.php?title=Hivenudger_2
        ///.........O.O
        ///........O..O
        ///.......OO
        ///......O...O
        ///.....OOO.O
        ///..OO
        ///.O...OOOOO.......OOOO.....O..O
        ///O...O............O...O...O
        ///O.....OO.........O.......O...O
        ///OOO...OOOO........O..O...OOOO
        ///.O.......O
        ///.OO...................OO
        ///.O.O..................OO
        ///.OO..OO.O........O.O..OO
        ///..O.OOO.O...O.OOOO.O..OO
        ///.........OO.O.OO..O...OO...OOO
        ///....OOOOOO.OO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hivenudger2 {
            get {
                return ResourceManager.GetString("hivenudger2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Honeycomb
        ///!A symmetric still life.
        ///!http://www.conwaylife.com/wiki/index.php?title=Honeycomb
        ///..OO
        ///.O..O
        ///O.OO.O
        ///.O..O
        ///..OO
        ///.
        /// </summary>
        internal static string honeycomb {
            get {
                return ResourceManager.GetString("honeycomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Honey farm
        ///!A common formation of four beehives.
        ///!http://www.conwaylife.com/wiki/index.php?title=Honey_farm
        ///......O
        ///.....O.O
        ///.....O.O
        ///......O
        ///
        ///.OO.......OO
        ///O..O.....O..O
        ///.OO.......OO
        ///
        ///......O
        ///.....O.O
        ///.....O.O
        ///......O
        ///.
        /// </summary>
        internal static string honeyfarm {
            get {
                return ResourceManager.GetString("honeyfarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Hooks
        ///!A period 5 oscillator.
        ///!www.conwaylife.com/wiki/Hooks
        ///......OO
        ///O.OO.O.O
        ///OO.O.O
        ///....OO
        ///.....O
        ///
        ///.......OO
        ///.......O
        ///........OOO
        ///..........O
        ///.
        /// </summary>
        internal static string hooks {
            get {
                return ResourceManager.GetString("hooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Hook with tail
        ///!An 8-cell still life that went for a long time with no well-established name.
        ///!http://www.conwaylife.com/wiki/index.php?title=Hook_with_tail
        ///OO
        ///.O
        ///.O.OO
        ///..O.O
        ///.
        /// </summary>
        internal static string hookwithtail {
            get {
                return ResourceManager.GetString("hookwithtail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: House
        ///!An induction coil.
        ///!http://www.conwaylife.com/wiki/index.php?title=House
        ///.OOO
        ///O...O
        ///OO.OO
        ///.
        /// </summary>
        internal static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Interchange
        ///!A common formation of six blinkers.
        ///!www.conwaylife.com/wiki/index.php?title=Interchange
        ///..OOO....OOO
        ///
        ///O............O
        ///O............O
        ///O............O
        ///
        ///..OOO....OOO
        ///.
        /// </summary>
        internal static string interchange {
            get {
                return ResourceManager.GetString("interchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Iwona
        ///!Author: Andrew Okrasinski
        ///!A methuselah with lifespan 28786. Found on August 20, 2004.
        ///!www.conwaylife.com/wiki/index.php?title=Iwona
        ///..............OOO
        ///
        ///
        ///
        ///
        ///
        ///..O
        ///...OO
        ///...O..............O
        ///..................O
        ///..................O
        ///...................O
        ///..................OO
        ///.......OO
        ///........O
        ///
        ///
        ///
        ///
        ///OO
        ///.O
        ///.
        /// </summary>
        internal static string iwona {
            get {
                return ResourceManager.GetString("iwona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Jack
        ///!Author: Robert Wainwright
        ///!A period 4 oscillator found in April 1984.
        ///!www.conwaylife.com/wiki/index.php?title=Jack
        ///...O.....O
        ///...OO...OO
        ///O..OO...OO..O
        ///OOO..O.O..OOO
        ///.....O.O
        ///OOO..O.O..OOO
        ///O..OO...OO..O
        ///...OO...OO
        ///...O.....O
        ///.
        /// </summary>
        internal static string jack {
            get {
                return ResourceManager.GetString("jack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Jam
        ///!Author: Achim Flammenkamp
        ///!A period 3 oscillator.
        ///!www.conwaylife.com/wiki/index.php?title=Jam
        ///...OO
        ///..O..O
        ///O..O.O
        ///O...O
        ///O
        ///...O
        ///.OO
        ///.
        /// </summary>
        internal static string jam {
            get {
                return ResourceManager.GetString("jam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Karel&apos;s p15
        ///!Author: Karel Suhajda
        ///!A period 15 oscillator discovered on December 11, 2002
        ///!http://www.conwaylife.com/wiki/index.php?title=Karel&apos;s_p15
        ///..O....O
        ///..OOOOOO
        ///..O....O
        ///
        ///
        ///
        ///..OOOOOO
        ///.O......O
        ///O........O
        ///.O......O
        ///..OOOOOO
        ///.
        /// </summary>
        internal static string karelsp15 {
            get {
                return ResourceManager.GetString("karelsp15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Killer candlefrobras
        ///!An arrangement of two candlefrobras that act in some ways like killer toads.
        ///!www.conwaylife.com/wiki/index.php?title=Killer_candlefrobras
        ///....O...........O
        ///OO.O.OO.O...O.OO.O.OO
        ///OO.O...O.O.O.O...O.OO
        ///...O....O...O....O
        ///...OO...........OO
        ///
        ///
        ///.........OOO
        ///.........O..O
        ///.........O
        ///.........O...O
        ///.........O...O
        ///.........O
        ///..........O.O
        ///.
        /// </summary>
        internal static string killercandlefrobras {
            get {
                return ResourceManager.GetString("killercandlefrobras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Killer toads
        ///!A pair of toads acting together so that they can eat things.
        ///!www.conwaylife.com/wiki/index.php?title=Killer_toads
        ///.OOO
        ///OOO
        ///
        ///
        ///
        ///OOO
        ///.OOO
        ///.
        /// </summary>
        internal static string killertoads {
            get {
                return ResourceManager.GetString("killertoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: LWSS
        ///!Author: John Conway
        ///!The smallest known orthogonally moving spaceship, and the second most common spaceship (after the glider).
        ///!www.conwaylife.com/wiki/index.php?title=Lightweight_spaceship
        ///.O..O
        ///O
        ///O...O
        ///OOOO
        ///.
        /// </summary>
        internal static string lwss {
            get {
                return ResourceManager.GetString("lwss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Mango
        ///!The twelfth most common still life.
        ///!http://www.conwaylife.com/wiki/index.php?title=Mango
        ///.OO
        ///O..O
        ///.O..O
        ///..OO
        ///.
        /// </summary>
        internal static string mango {
            get {
                return ResourceManager.GetString("mango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Mathematician
        ///!Author: David Buckingham
        ///!A period 5 oscillator found in 1972.
        ///!http://www.conwaylife.com/wiki/index.php?title=Mathematician
        ///....O
        ///...O.O
        ///...O.O
        ///..OO.OO
        ///O.......O
        ///OOO...OOO
        ///
        ///OOOOOOOOO
        ///O.......O
        ///...OOOO
        ///...O..OO
        ///.
        /// </summary>
        internal static string mathematician {
            get {
                return ResourceManager.GetString("mathematician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Max
        ///!Author: Tim Coe
        ///!A spacefiller that fills the space with chicken wire.
        ///!www.conwaylife.com/wiki/index.php?title=Max
        ///..................O
        ///.................OOO
        ///............OOO....OO
        ///...........O..OOO..O.OO
        ///..........O...O.O..O.O
        ///..........O....O.O.O.O.OO
        ///............O....O.O...OO
        ///OOOO.....O.O....O...O.OOO
        ///O...OO.O.OOO.OO.........OO
        ///O.....OO.....O
        ///.O..OO.O..O..O.OO
        ///.......O.O.O.O.O.O.....OOOO
        ///.O..OO.O..O..O..OO.O.OO...O
        ///O.....OO...O.O.O...OO.....O
        ///O...OO.O.OO..O..O..O.OO..O
        ///OOOO.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Mazing
        ///!Author: David Buckingham
        ///!A period 4 oscillator.
        ///!www.conwaylife.com/wiki/index.php?title=Mazing
        ///...OO
        ///.O.O
        ///O.....O
        ///.O...OO
        ///
        ///...O.O
        ///....O
        ///.
        /// </summary>
        internal static string mazing {
            get {
                return ResourceManager.GetString("mazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Moose antlers
        ///!A simple still life.
        ///!www.conwaylife.com/wiki/index.php?title=Moose_antlers
        ///OO.....OO
        ///O.......O
        ///.OOO.OOO
        ///...O.O
        ///....O
        ///.
        /// </summary>
        internal static string mooseantlers {
            get {
                return ResourceManager.GetString("mooseantlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Multum in parvo
        ///!Author: Charles Corderman
        ///!A methuselah with lifespan 3933.
        ///!www.conwaylife.com/wiki/index.php?title=Multum_in_parvo
        ///...OOO
        ///..O..O
        ///.O
        ///O
        ///.
        /// </summary>
        internal static string multuminparvo {
            get {
                return ResourceManager.GetString("multuminparvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: p35.1
        ///!Author: Dean Hickerson
        ///!The first known period 35 oscillator
        ///!http://www.conwaylife.com/wiki/index.php?title=P35_beehive_hassler
        ///...................................OO....OO
        ///...................................O.O..O.O...........................OO
        ///.....................................O..O......OO....OO........OO...O..O
        ///....................................O....O......O....O.O........O...OO
        ///..........................O.........OO..OO......O.OO.O..O.......O.OO..OOOO.OO
        ///..................... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p35beehivehassler {
            get {
                return ResourceManager.GetString("p35beehivehassler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: P36 toad hassler
        ///!Author: Robert Wainwright
        ///!The first period 36 oscillator to be discovered
        ///OO................OO
        ///.O................O
        ///.O.O............O.O
        ///..OO............OO
        ///.......O....O
        ///.....OO.OOOO.OO
        ///.......O....O
        ///..OO............OO
        ///.O.O............O.O
        ///.O................O
        ///OO................OO
        ///...........O
        ///.........O..O
        ///.........O..O
        ///..........O
        ///OO................OO
        ///.O................O
        ///.O.O............O.O
        ///..OO............OO
        ///.......O....O
        ///.....OO.OOOO.OO
        ///.......O....O
        ///..OO.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p36toadhassler {
            get {
                return ResourceManager.GetString("p36toadhassler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: P5 reflector
        ///!A period 5 oscillator that can act as a glider reflector.
        ///!www.conwaylife.com/wiki/P5_reflector
        ///........OO
        ///.....O..O.O
        ///....O.O.O.O
        ///...O.O.O..OO
        ///...O...O.O
        ///OO.O.O.O.OOO.O........OO
        ///O.O....O..O.......OO..OO
        ///..O.OOO....O...O.O.O
        ///..O..O.....O......O
        ///...O...O.OO...O..........OO
        ///....OOO.OO.OO.......OO....O
        ///......O....O........OO...O
        ///.......OOO.O.....O......OO
        ///..........O.OO...OO.....O..O
        ///.........O..O......O........O
        ///.........OO..OOOO..O.......OO
        ///
        ///.............OOO...O
        ///... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p5reflector {
            get {
                return ResourceManager.GetString("p5reflector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Pipsquirter 1
        ///!Author: Noam Elkies
        ///!A period 6 pipsquirter found in November 1997.
        ///!www.conwaylife.com/wiki/index.php?title=Pipsquirter_1
        ///...OO.OO
        ///.OOO.O.OOO
        ///O....O....O
        ///O.OO..OO.O.O
        ///.O..OO...O.O
        ///..OO..OO.O.O.OO
        ///....O....O.O.OO
        ///....OOOO.OO
        ///........O
        ///......O.O
        ///......OO
        ///.
        /// </summary>
        internal static string pipsquirter1 {
            get {
                return ResourceManager.GetString("pipsquirter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Pipsquirter 2
        ///!Author: Noam Elkies
        ///!A period 7 pipsquirter oscillator.
        ///!www.conwaylife.com/wiki/index.php?title=Pipsquirter_2
        ///......OO
        ///......O.O
        ///........O
        ///...O..O.OO
        ///...OOOO
        ///.......OO..OO
        ///...OOOO
        ///O.O...O.OO
        ///OO.OO.O.O
        ///...O....O
        ///...O.O.O.OO
        ///OO.O.O.O.O
        ///O.O....O.O
        ///..O.OO.O..OO
        ///..O.O...O.O
        ///.OO..O.OO.O
        ///..O.O....O
        ///..O...OOO
        ///...OO.O
        ///........OOO
        ///.OOOOOOO..O
        ///.O..O..O
        ///.
        /// </summary>
        internal static string pipsquirter2 {
            get {
                return ResourceManager.GetString("pipsquirter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Piston
        ///!A period 2 oscillator found in 1971.
        ///!www.conwaylife.com/wiki/index.php?title=Piston
        ///OO.......OO
        ///O.O..O..O.O
        ///..OOOO..O
        ///O.O..O..O.O
        ///OO.......OO
        ///.
        /// </summary>
        internal static string piston {
            get {
                return ResourceManager.GetString("piston", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Pond
        ///!A still life.
        ///!www.conwaylife.com/wiki/index.php?title=Pond
        ///.OO
        ///O..O
        ///O..O
        ///.OO
        ///.
        /// </summary>
        internal static string pond {
            get {
                return ResourceManager.GetString("pond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Popover
        ///!Author: Robert Wainwright
        ///!A period 32 oscillator that works by hassling a pi-heptomino.
        ///!www.conwaylife.com/wiki/index.php?title=Popover
        ///.....................O
        ///....................O.O
        ///
        ///.............OO...O...OO
        ///.............OO..O.....O
        ///..................O.O
        ///....................OO
        ///..............OO
        ///...OO........O..O
        ///.O.O.........O.O....O
        ///O.....O.......O.....O
        ///.O...OO..OOO........O
        ///
        ///...O.O................OO...OO
        ///....O............O...O..O..OO
        ///........O.......OOO...O.O
        ///....... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string popover {
            get {
                return ResourceManager.GetString("popover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Pre-pulsar shuttle 29 v2
        ///!A period 29 pre-pulsar shuttle oscillator.
        ///!www.conwaylife.com/wiki/index.php?title=Pre-pulsar_shuttle_29
        ///...............O
        ///.............OOO
        ///............O
        ///............OO
        ///
        ///.O
        ///O.O...OOO
        ///.O....O.O......OO
        ///......OOO......OO
        ///
        ///
        ///...................OO
        ///......OOO..........OO.....OO
        ///.O....O.O.................O
        ///O.O...OOO...............O.O
        ///.O......................OO
        ///
        ///
        ///
        ///.............OOO...OOO
        ///.............O.O...O.O
        ///.............OOO...OOO
        ///
        ///
        ///
        ///.............O....... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prepulsarshuttle29v2 {
            get {
                return ResourceManager.GetString("prepulsarshuttle29v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Pre-pulsar spaceship
        ///!Author: David Bell
        ///!A period 30 orthogonal c/5 spaceship in which two spiders push a pre-pulsar. Found
        ///!in May 1998.
        ///!www.conwaylife.com/wiki/index.php?title=Pre-pulsar_spaceship
        ///...............................O.....O
        ///..............................OOO...OOO
        ///
        ///
        ///
        ///..OO.....OO.....OO.....OO...................OO.....OO.....OO.....OO
        ///O...O...O..O...O..O...O...O...............O...O...O..O...O..O...O...O
        ///O...O.O.OOO.....OOO.O.O...O...............O...O.O.OOO.....OOO.O.O...O
        ///O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prepulsarspaceship {
            get {
                return ResourceManager.GetString("prepulsarspaceship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Pressure cooker
        ///!A period 3 oscillator found by the MIT group in September 1971.
        ///!www.conwaylife.com/wiki/index.php?title=Pressure_cooker
        ///.....O
        ///....O.O
        ///....O.O
        ///...OO.OO
        ///O.O.....O.O
        ///OO.O.O.O.OO
        ///...O...O
        ///...O...O
        ///....OOO
        ///
        ///...O.OO
        ///...OO.O
        ///.
        /// </summary>
        internal static string pressurecooker {
            get {
                return ResourceManager.GetString("pressurecooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Protein
        ///!Author: David Buckingham
        ///!A period 3 oscillator found in November 1972.
        ///!www.conwaylife.com/wiki/index.php?title=Protein
        ///....OO
        ///....O
        ///......O
        ///..OOOO.O.OO
        ///.O.....O.O..O
        ///.O..OO.O.O.OO
        ///OO.O.....O
        ///...O..OO.O
        ///...O....O
        ///....OOOO
        ///
        ///....OO
        ///....OO
        ///.
        /// </summary>
        internal static string protein {
            get {
                return ResourceManager.GetString("protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Pseudo-barberpole
        ///!Author: Achim Flammenkamp
        ///!Found in August 1994. In terms of its minimum population of 15, this is the smallest known period 5 oscillator (as of January 2009).
        ///..........OO
        ///...........O
        ///.........O
        ///.......O.O
        ///
        ///.....O.O
        ///
        ///...O.O
        ///
        ///..OO
        ///O
        ///OO
        ///.
        /// </summary>
        internal static string pseudobarberpole {
            get {
                return ResourceManager.GetString("pseudobarberpole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: R2D2
        ///!Author: Peter Raynham
        ///!A period 8 oscillator.
        ///!http://www.conwaylife.com/wiki/index.php?title=R2D2
        ///.....O
        ///....O.O
        ///...O.O.O
        ///...O.O.O
        ///OO.O...O.OO
        ///OO.O...O.OO
        ///...O...O
        ///...O.O.O
        ///....O.O
        ///.....O
        ///.
        /// </summary>
        internal static string r2d2 {
            get {
                return ResourceManager.GetString("r2d2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Revolver
        ///!A period 2 oscillator and flipper.
        ///!www.conwaylife.com/wiki/index.php?title=Revolver
        ///O............O
        ///OOO....O...OOO
        ///...O.O.O..O
        ///..O......O.O
        ///..O.O......O
        ///...O..O.O.O
        ///OOO...O....OOO
        ///O............O
        ///.
        /// </summary>
        internal static string revolver {
            get {
                return ResourceManager.GetString("revolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Sailboat
        ///!Author: Robert Wainwright
        ///!A boat that is hassled by a Kok&apos;s galaxy, a figure eight, and two eater 3s. Found in June 1984.
        ///!www.conwaylife.com/wiki/index.php?title=Sailboat
        ///........O...........O
        ///.......O.O.........O.O
        ///........O...........O
        ///
        ///......OOOOO.......OOOOO
        ///.....O....O.......O....O
        ///....O..O.............O..O
        ///.O..O.OO.............OO.O..O
        ///O.O.O.....O.......OO....O.O.O
        ///.O..O....O.O.....O..O...O..O
        ///....OO..O..O......O.O..OO
        ///.........OO........O
        ///.............OO
        ///........... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sailboat {
            get {
                return ResourceManager.GetString("sailboat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Schick engine
        ///!Author: Paul Schick
        ///!An orthogonal c/2 tagalong found in 1972.
        ///!www.conwaylife.com/wiki/index.php?title=Schick_engine
        ///.O..O
        ///O
        ///O...O
        ///OOOO.........OO
        ///......OOO.....OO
        ///......OO.OO......OOO
        ///......OOO.....OO
        ///OOOO.........OO
        ///O...O
        ///O
        ///.O..O
        ///.
        /// </summary>
        internal static string schickengine {
            get {
                return ResourceManager.GetString("schickengine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....OO......OO....
        ///...O..O....O..O...
        ///...O.O......O.O...
        ///.OO..OOO..OOO..OO.
        ///O......O..O......O
        ///O.OO..........OO.O
        ///.O.O..........O.O.
        ///...OO...OO...OO...
        ///.......O.O........
        ///.......OO.........
        ///...OO........OO...
        ///.O.O..........O.O.
        ///O.OO..........OO.O
        ///O......O..O......O
        ///.OO..OOO..OOO..OO.
        ///...O.O......O.O...
        ///...O..O....O..O...
        ///....OO......OO.....
        /// </summary>
        internal static string Ship_In_a_Bottle {
            get {
                return ResourceManager.GetString("Ship_In_a_Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Silver&apos;s p5
        ///!Author: Stephen Silver
        ///!A period 5 oscillator found in February 2000.
        ///!www.conwaylife.com/wiki/index.php?title=Silver&apos;s_p5
        ///OO
        ///O
        ///.O..O
        ///...OO
        ///...O...O.OO
        ///..O....OO.O
        ///..OO
        ///.
        /// </summary>
        internal static string silversp5 {
            get {
                return ResourceManager.GetString("silversp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Snorkel loop
        ///!The 83rd most common still life.
        ///!http://www.conwaylife.com/wiki/index.php?title=Snorkel_loop
        ///..OO
        ///.O..O
        ///..O.O
        ///O.O.OO
        ///OO
        ///.
        /// </summary>
        internal static string snorkelloop {
            get {
                return ResourceManager.GetString("snorkelloop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..........O....................
        ///..........O...............OO...
        ///......OO.O.OOO..........OO...O.
        ///O.OO.OO.OO..O.O...OO.OOOO......
        ///O...OO..O.OO..OOO..O.OO..OO...O
        ///O.OO....OOO.O.OOO......OO..O...
        ///........OO.O...............O..O
        ///O.OO....OOO.O.OOO......OO..O...
        ///O...OO..O.OO..OOO..O.OO..OO...O
        ///O.OO.OO.OO..O.O...OO.OOOO......
        ///......OO.O.OOO..........OO...O.
        ///..........O...............OO...
        ///..........O.....................
        /// </summary>
        internal static string Sparky {
            get {
                return ResourceManager.GetString("Sparky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Table on table
        ///!Two tables with one row of dead cells between them.
        ///!http://www.conwaylife.com/wiki/index.php?title=Table_on_table
        ///O..O
        ///OOOO
        ///
        ///OOOO
        ///O..O
        ///.
        /// </summary>
        internal static string tableontable {
            get {
                return ResourceManager.GetString("tableontable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Traffic circle
        ///!A traffic circle works by hassling a traffic jam so that it moves around in a circle.
        ///!www.conwaylife.com/wiki/index.php?title=Traffic_circle
        ///.....................OO....OO
        ///.....................O.O..O.O
        ///.......................O..O
        ///......................OO..OO
        ///.....................OOO..OOO
        ///.......................O..O
        ///...............................O
        ///..............................O.OO
        ///..................................O
        ///..........................O...O..O.O
        ///.................. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trafficcircle {
            get {
                return ResourceManager.GetString("trafficcircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Traffic jam
        ///!In this reaction, two traffic lights interact in such a way as to reappear after 25 generations with an extra 6 spaces between them.
        ///!www.conwaylife.com/wiki/index.php?title=Traffic_jam
        ///..OOO
        ///...........OOO
        ///O.....O
        ///O.....O..O.....O
        ///O.....O..O.....O
        ///.........O.....O
        ///..OOO
        ///...........OOO
        ///.
        /// </summary>
        internal static string trafficjam {
            get {
                return ResourceManager.GetString("trafficjam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Tripole
        ///!The barberpole of length 3.
        ///!www.conwaylife.com/wiki/index.php?title=Tripole
        ///OO
        ///O.O
        ///
        ///..O.O
        ///.....O
        ///....OO
        ///.
        /// </summary>
        internal static string tripole {
            get {
                return ResourceManager.GetString("tripole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .OO........................
        ///.OO........................
        ///...........................
        ///...............O...........
        ///OO.............OO........OO
        ///OO..............OO.......OO
        ///...........OO..OO..........
        ///...........................
        ///...........................
        ///...........................
        ///...........OO..OO..........
        ///OO..............OO.........
        ///OO.............OO..........
        ///...............O...........
        ///...........................
        ///.OO........................
        ///.OO.........................
        /// </summary>
        internal static string Twin_Bees {
            get {
                return ResourceManager.GetString("Twin_Bees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Unicycle
        ///!A period 6 oscillator made up of four copies of unix.
        ///!www.conwaylife.com/wiki/index.php?title=Unicycle
        ///..OO...OOOO
        ///..OO..O....O
        ///OO.O..O...O.O
        ///OOO....O...O.O
        ///.............O
        ///.............O
        ///.OO.......O..O
        ///O..O.......OO
        ///O
        ///O
        ///O.O...O....OOO
        ///.O.O...O..O.OO
        ///..O....O..OO
        ///...OOOO...OO
        ///.
        /// </summary>
        internal static string unicycle {
            get {
                return ResourceManager.GetString("unicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Unix
        ///!Author: David Buckingham
        ///!A period 6 oscillator that consists of two blocks eating a barge.
        ///!http://www.conwaylife.com/wiki/index.php?title=Unix
        ///.OO
        ///.OO
        ///
        ///.O
        ///O.O
        ///O..O..OO
        ///....O.OO
        ///..OO
        ///.
        /// </summary>
        internal static string unix {
            get {
                return ResourceManager.GetString("unix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Washerwoman
        ///!Author: Earl Abbe
        ///!A period 18 fuse that burns tubs.
        ///!www.conwaylife.com/wiki/index.php?title=Washerwoman
        ///O
        ///OO....O.....O.....O.....O.....O.....O.....O.....O.....O
        ///OOO..O.O...O.O...O.O...O.O...O.O...O.O...O.O...O.O...O.O
        ///OO....O.....O.....O.....O.....O.....O.....O.....O.....O
        ///O
        ///.
        /// </summary>
        internal static string washerwoman {
            get {
                return ResourceManager.GetString("washerwoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Why not
        ///!Author: David Buckingham
        ///!A period 2 oscillator found in July 1977 that is very similar to by flops.
        ///!www.conwaylife.com/wiki/index.php?title=Why_not
        ///...O
        ///...O.O
        ///.O
        ///O.OOOOO
        ///.O
        ///...O.O
        ///...O
        ///.
        /// </summary>
        internal static string whynot {
            get {
                return ResourceManager.GetString("whynot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .................OO..............................
        ///.............OO....O.............................
        ///............OOO.O................................
        ///O.OO..OO...O...OOOO.O.O....OO.......OO...........
        ///O....OO..O........O.OOO....O....OO.O..O.OO.O.....
        ///O.OO....OO.OO....O...........O...O.O.OO.O.OO.....
        ///......O.......O.............OO.....O..O.O...OO...
        ///.....O.........O.O....OOO...O....O..O.O.OOO...O..
        ///.....O.........O.O....OOO.OO.O..OO.O.O...O..OO.O.
        ///......O.......O.............OO.O...OO....OO....O.
        ///O. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wickstretcher {
            get {
                return ResourceManager.GetString("Wickstretcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Name: Wing
        ///!An induction coil.
        ///!www.conwaylife.com/wiki/index.php?title=Wing
        ///.OO
        ///O..O
        ///.O.O
        ///..OO
        ///.
        /// </summary>
        internal static string wing {
            get {
                return ResourceManager.GetString("wing", resourceCulture);
            }
        }
    }
}
