//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHGameOfLife {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LargePops {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LargePops() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHGameOfLife.LargePops", typeof(LargePops).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1110000000000
        ///1000000000110
        ///0100000011101
        ///0001100110000
        ///0000100000000
        ///0000000010000
        ///0000110001000
        ///0001010110000
        ///0001010010110
        ///0010000110000
        ///0011000000000
        ///0011000000000.
        /// </summary>
        internal static string Canada_Goose {
            get {
                return ResourceManager.GetString("Canada_Goose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000110000000
        ///00000001100000000
        ///00000000010000000
        ///00000000000110000
        ///00000000001000000
        ///00000000000000000
        ///00000000010011000
        ///01100000110000100
        ///11000001000001000
        ///00100001010001100
        ///00001001000011010
        ///00001100000001100
        ///00000000100001011
        ///00000001010010110
        ///00000000100000000.
        /// </summary>
        internal static string Grow_By_One {
            get {
                return ResourceManager.GetString("Grow_By_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000011000000110000
        ///000100100001001000
        ///000101000000101000
        ///011001110011100110
        ///100000010010000001
        ///101100000000001101
        ///010100000000001010
        ///000110001100011000
        ///000000010100000000
        ///000000011000000000
        ///000110000000011000
        ///010100000000001010
        ///101100000000001101
        ///100000010010000001
        ///011001110011100110
        ///000101000000101000
        ///000100100001001000
        ///000011000000110000.
        /// </summary>
        internal static string Ship_In_a_Bottle {
            get {
                return ResourceManager.GetString("Ship_In_a_Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000100000000000000000000
        ///0000000000100000000000000011000
        ///0000001101011100000000001100010
        ///1011011011001010001101111000000
        ///1000110010110011100101100110001
        ///1011000011101011100000011001000
        ///0000000011010000000000000001001
        ///1011000011101011100000011001000
        ///1000110010110011100101100110001
        ///1011011011001010001101111000000
        ///0000001101011100000000001100010
        ///0000000000100000000000000011000
        ///0000000000100000000000000000000.
        /// </summary>
        internal static string Sparky {
            get {
                return ResourceManager.GetString("Sparky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011000000000000000000000000
        ///011000000000000000000000000
        ///000000000000000000000000000
        ///000000000000000100000000000
        ///110000000000000110000000011
        ///110000000000000011000000011
        ///000000000001100110000000000
        ///000000000000000000000000000
        ///000000000000000000000000000
        ///000000000000000000000000000
        ///000000000001100110000000000
        ///110000000000000011000000000
        ///110000000000000110000000000
        ///000000000000000100000000000
        ///000000000000000000000000000
        ///011000000000000000000000000
        ///011000000000000000000000000.
        /// </summary>
        internal static string Twin_Bees {
            get {
                return ResourceManager.GetString("Twin_Bees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000011000000000000000000000000000000
        ///0000000000000110000100000000000000000000000000000
        ///0000000000001110100000000000000000000000000000000
        ///1011001100010001111010100001100000001100000000000
        ///1000011001000000001011100001000011010010110100000
        ///1011000011011000010000000000010001010110101100000
        ///0000001000000010000000000000110000010010100011000
        ///0000010000000001010000111000100001001010111000100
        ///0000010000000001010000111011010011010100010011010
        ///0000001000000010000000000000110100011000011000010
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wickstretcher {
            get {
                return ResourceManager.GetString("Wickstretcher", resourceCulture);
            }
        }
    }
}
